export const CAR_LIST_REQUEST = 'CAR_LIST_REQUEST';
export const CAR_LIST_SUCCESS = 'CAR_LIST_SUCCESS';
export const CAR_LIST_FAIL = 'CAR_LIST_FAIL';
export const CAR_ADD_SUCCESS = 'CAR_ADD_SUCCESS';
export const CAR_UPDATE_SUCCESS = 'CAR_UPDATE_SUCCESS';
export const CAR_DELETE_SUCCESS = 'CAR_DELETE_SUCCESS';
